# Generated by Django 3.1.4 on 2020-12-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goplaces', '0003_auto_20201207_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionnaire',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(default='def', max_length=255, verbose_name='Ответ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='questions', to='goplaces.Answer', verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=255, verbose_name='Вопрос'),
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
    ]
