# Generated by Django 3.1.4 on 2020-12-08 17:44

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('goplaces', '0006_auto_20201208_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='another_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='place',
            name='poster',
            field=models.ImageField(blank=True, upload_to='goplaces/img/posters/', verbose_name='Постер'),
        ),
    ]
