# Generated by Django 3.1.4 on 2020-12-08 17:48

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('goplaces', '0008_auto_20201208_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='another_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
