# Generated by Django 3.1.4 on 2020-12-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goplaces', '0009_auto_20201208_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='average_check',
            field=models.PositiveIntegerField(default=0, verbose_name='Средний чек'),
        ),
        migrations.AlterField(
            model_name='place',
            name='poster',
            field=models.ImageField(upload_to='posters/', verbose_name='Постер'),
        ),
    ]
