# Generated by Django 3.1.4 on 2020-12-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goplaces', '0010_auto_20201209_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='another_tags',
        ),
        migrations.AddField(
            model_name='place',
            name='url',
            field=models.SlugField(default='resp', max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
